# Configuration file for JuliaFormatter.jl
# For more information see: https://domluna.github.io/JuliaFormatter.jl/stable/config/

always_for_in = true
always_use_return = true
margin = 80
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = false
format_docstrings = true
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
trailing_comma = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
import_to_using = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
indent_submodule = true
verbose = true
overwrite = true
normalize_line_endings = "unix"
